subjects = [
    "Shah Rukh Khan",
    "Elon Musk",
    "Narendra Modi",
    "Amitabh Bachchan",
    "Deepika Padukone",
    "Alia Bhatt",
    "Priyanka Chopra",
    "Salman Khan",
    "Akshay Kumar",
    "Ranveer Singh",
    "Virat Kohli",
    "MS Dhoni",
    "Sachin Tendulkar",
    "PV Sindhu",
    "Neeraj Chopra",
    "Arijit Singh",
    "Hrithik Roshan",
    "Kareena Kapoor",
    "Katrina Kaif",
    "Anushka Sharma",
    "Taapsee Pannu",
    "Rajinikanth",
    "Kamal Haasan",
    "A.R. Rahman",
    "Sushant Singh Rajput",
    "Kangana Ranaut",
    "Ayushmann Khurrana",
    "Kriti Sanon",
    "Jacqueline Fernandez",
    "Tiger Shroff",
    "Parineeti Chopra",
    "Anil Kapoor",
    "Rani Mukerji",
    "Nawazuddin Siddiqui",
    "Vidya Balan",
    "Ranbir Kapoor",
    "Kiara Advani",
    "Disha Patani",
    "Bhumi Pednekar",
    "Rajkummar Rao",
    "Sidharth Malhotra",
    "Varun Dhawan",
    "Sanjay Dutt",
    "Karan Johar",
    "Farhan Akhtar",
    "Zoya Akhtar",
    "Aamir Khan",
    "Kajol",
    "Sonam Kapoor",
    "Vicky Kaushal",
]

actions = [
    "was riding",
    "was spotted flying",
    "danced with",
    "secretly met",
    "was caught painting",
    "started a new business",
    "adopted a tiger",
    "launched a rocket",
    "discovered a hidden treasure",
    "vanished mysteriously",
    "was arrested",
    "won a marathon",
    "climbed a mountain",
    "swam across the river",
    "broke a world record",
    "cooked a feast",
    "sang a new song",
    "wrote a bestseller",
    "traveled to Mars",
    "hacked a computer",
    "stole a diamond",
    "donated a million",
    "invented a gadget",
    "piloted a drone",
    "hosted a party",
    "rode a lion",
    "broke into a museum",
    "built a robot",
    "played a cricket match",
    "acted in a reality show",
    "went undercover",
    "created a virus",
    "rescued a child",
    "opened a restaurant",
    "danced ballet",
    "formed a band",
    "painted a mural",
    "attended a secret meeting",
    "won a lottery",
    "started a cult",
    "saved a dog",
    "disappeared in jungle",
    "kidnapped by aliens",
    "became invisible",
    "got lost in desert",
    "repaired a spaceship",
    "ran a marathon",
    "walked on water",
    "filmed a documentary",
    "surprised fans",
    "donated blood",
]

places = [
    "at India Gate",
    "in a buffalo cart",
    "near the Taj Mahal",
    "inside a haunted mansion",
    "on Mars",
    "at a secret beach",
    "with a group of aliens",
    "inside a forest cave",
    "on top of a skyscraper",
    "at a famous cafe",
    "in a submarine",
    "during a flood",
    "on a rollercoaster",
    "at a music festival",
    "inside a volcano",
    "on a yacht",
    "at a political rally",
    "in a secret bunker",
    "at a sports stadium",
    "at a zoo",
    "on a helicopter",
    "in a hot air balloon",
    "at a royal palace",
    "inside a cave",
    "during a storm",
    "on a bridge",
    "in an abandoned factory",
    "at a nightclub",
    "in a spaceship",
    "at a theme park",
    "on a deserted island",
    "in a skyscraper",
    "near a waterfall",
    "on a mountain peak",
    "at a fireworks show",
    "in a library",
    "on a racetrack",
    "at a fashion show",
    "during a parade",
    "at a university",
    "at the airport",
    "on a cruise ship",
    "inside a mansion",
    "at a movie set",
    "on a ski slope",
    "at a conference",
    "in a forest",
    "near a lighthouse",
    "at a monastery",
    "in an underground tunnel",
]
