quiz_hints_100 = {
    # 30 General Knowledge (GK)
    "What is the capital of France?": "City of Lights",
    "Who wrote 'Hamlet'?": "Famous English playwright",
    "Largest planet in the solar system?": "Fifth from the sun",
    "National animal of India?": "Striped big cat",
    "Smallest continent?": "Country continent",
    "Which is the longest river?": "Flows through Egypt",
    "Who invented the telephone?": "Bell inventor",
    "Currency of Japan?": "Yen symbol",
    "Who painted Mona Lisa?": "Renaissance artist",
    "Nearest star to Earth?": "Center of our system",
    "Red Planet in solar system?": "Mars nickname",
    "Which planet is called Blue Planet?": "Our home",
    "Who discovered penicillin?": "Antibiotic pioneer",
    "Tallest mountain in the world?": "Himalayas' peak",
    "Largest mammal?": "Ocean giant",
    "Human body's largest organ?": "Covers the body",
    "Fastest land animal?": "Spots and speed",
    "Who was the first President of USA?": "Revolutionary leader",
    "Deepest ocean?": "Pacific basin",
    "National flower of Japan?": "Pink petals",
    "Name the largest desert in the world?": "Hot, sandy",
    "Which gas do plants take in for photosynthesis?": "Green process gas",
    "Capital of Brazil?": "Modern planned city",
    "Founder of Microsoft?": "Billionaire techie",
    "What is the chemical symbol for water?": "Two H, one O",
    "Who invented the light bulb?": "Electric pioneer",
    "Which metal is liquid at room temperature?": "Heavy and shiny",
    "What is the powerhouse of a cell?": "Energy center",
    "Who is known as the father of computers?": "Analytical engine",
    "What is the speed of light?": "300,000 km/s approx",
    # 30 cricket questions
    "Number of players in a cricket team?": "Eleven per side",
    "Shape of cricket ball?": "Not round",
    "Length of cricket pitch (yards)?": "Between wickets",
    "How many stumps in a wicket?": "Three vertical sticks",
    "What does LBW stand for in cricket?": "Common dismissal type",
    "What is a hat-trick in cricket?": "Three wickets in a row",
    "First Cricket World Cup winner?": "Caribbean team",
    "Nickname of Sachin Ramesh Tendulkar?": "Master Blaster",
    "Trophy contested between England and Australia?": "Ash-filled urn",
    "Cricket's highest governing body?": "International authority",
    "Who holds the record for most runs in ODI World Cups?": "Indian batting legend",
    "Who was the first captain to win ICC ODI, T20 and Champions Trophy?": "MS Dhoni",
    "Who scored the fastest century in ODIs?": "South African batsman",
    "Which bowler took the first World Cup hat-trick?": "Indian fast bowler",
    "Who has the highest individual score in a World Cup match?": "New Zealand opener",
    "Who has the most wickets in World Cup history?": "Australian pacer",
    "Indian cricketer famous for helicopter shot?": "MS Dhoni",
    "Who is known as the Rawalpindi Express?": "Pakistani speedster",
    "Which country hosted the first ODI Cricket World Cup?": "England",
    "What is the maximum number of overs in an ODI?": "Limit is 50",
    "Who has the most Test wickets?": "Sri Lankan spinner",
    "Who scored the first double century in ODI cricket?": "Sachin Tendulkar",
    "Who is known as The Wall in cricket?": "Indian batsman",
    "Who is the youngest cricketer to score a Test century?": "Pakistani prodigy",
    "Who was the highest wicket-taker in the 2019 Cricket World Cup?": "Australian fast bowler",
    "Who scored the most sixes in international cricket?": "Caribbean big hitter",
    "Who was the first cricketer to take 10 wickets in an innings?": "English bowler",
    "Who has the highest individual score in Test cricket?": "West Indies legend",
    "Which cricketer has the nickname 'Boom Boom'?": "Pakistani all-rounder",
    "Who captained India to its first Cricket World Cup win?": "1983 captain",
    # 20 Indian celebrities
    "Cricketer known as 'God of Cricket'?": "Sachin Tendulkar",
    "Bollywood's King Khan?": "Shah Rukh Khan",
    "First Indian woman to win Miss World?": "1966 winner",
    "Chairman and MD of Reliance Industries?": "Mukesh Ambani",
    "Indian singer who composed 'Jai Ho'?": "Oscar winner",
    "Youngest Indian Nobel laureate for education activism?": "Malala Yousafzai",
    "Famous Indian badminton player?": "Olympian shuttler",
    "Actor known as 'Megastar' in Telugu cinema?": "Chiranjeevi",
    "Indian female tennis player famous internationally?": "Sania Mirza",
    "Co-founder of Infosys?": "Narayana Murthy",
    "Indian Prime Minister in 2024?": "Narendra Modi",
    "Indian classical dancer known worldwide?": "Padma Subrahmanyam",
    "Critically acclaimed Bollywood actress?": "Deepika Padukone",
    "Indian boxing world champion?": "Mary Kom",
    "Indian film director of 'Lagaan'?": "Ashutosh Gowariker",
    "Head of Indian Space Research Organization (ISRO)?": "S. Somanath",
    "Indian origin CEO of Alphabet Inc.?": "Sundar Pichai",
    "Indian author of 'The White Tiger'?": "Aravind Adiga",
    "Indian footballer famous internationally?": "Sunil Chhetri",
    "Indian classical musician?": "Pandit Ravi Shankar",
    # 20 Random facts
    "First human on the moon?": "Apollo 11 astronaut",
    "Largest desert?": "African hot sand",
    "Fastest land bird?": "Flightless runner",
    "Deepest point on Earth?": "Mariana Trench",
    "Chemical symbol for water?": "H and O atoms",
    "Tallest building (2025)?": "Dubai skyscraper",
    "Fruit with most vitamin C?": "Tropical guava",
    "Animal with trunk?": "Large mammal",
    "Main gas in air?": "Nitrogen component",
    "Largest bone in human body?": "Thigh bone",
    "Planet shaped like a potato?": "Dwarf planet",
    "Museum dedicated to failure?": "Celebrates flops",
    "Basketball court in Supreme Court?": "Highest court play",
    "Office chair inventor?": "Theory of evolution?",
    "Percentage of left-handed population?": "One tenth approx",
    "Jeans tiny pocket purpose?": "Watch holder",
    "Pope not allowed organ donor?": "True or false",
    "Only continent in four hemispheres?": "Africa",
    "Fastest growing plant?": "Giant grass",
    "Number of ridges on a US dime coin?": "One hundred plus",
}
