quiz_dict = {
    # 30 General Knowledge (GK) questions (extended from the original 20)
    "What is the capital of France?": "Paris",
    "Who wrote 'Hamlet'?": "William Shakespeare",
    "Largest planet in the solar system?": "Jupiter",
    "National animal of India?": "Bengal Tiger",
    "Smallest continent?": "Australia",
    "Which is the longest river?": "Nile",
    "Who invented the telephone?": "Alexander Graham Bell",
    "Currency of Japan?": "Japanese Yen",
    "Who painted Mona Lisa?": "Leonardo da Vinci",
    "Nearest star to Earth?": "Sun",
    "Red Planet in solar system?": "Mars",
    "Which planet is called Blue Planet?": "Earth",
    "Who discovered penicillin?": "Alexander Fleming",
    "Tallest mountain in the world?": "Mount Everest",
    "Largest mammal?": "Blue Whale",
    "Human body's largest organ?": "Skin",
    "Fastest land animal?": "Cheetah",
    "Who was the first President of USA?": "George Washington",
    "Deepest ocean?": "Pacific Ocean",
    "National flower of Japan?": "Cherry Blossom",
    "Name the largest desert in the world?": "Sahara",
    "Which gas do plants take in for photosynthesis?": "Carbon Dioxide",
    "Capital of Brazil?": "Brasília",
    "Founder of Microsoft?": "Bill Gates",
    "What is the chemical symbol for water?": "H2O",
    "Who invented the light bulb?": "Thomas Edison",
    "Which metal is liquid at room temperature?": "Mercury",
    "What is the powerhouse of a cell?": "Mitochondria",
    "Who is known as the father of computers?": "Charles Babbage",
    "What is the speed of light?": "299792 km/s",
    # 30 cricket questions (with some full names)
    "Number of players in a cricket team?": "Eleven",
    "Shape of cricket ball?": "Spherical",
    "Length of cricket pitch (yards)?": "Twenty Two",
    "How many stumps in a wicket?": "Three",
    "What does LBW stand for in cricket?": "Leg Before Wicket",
    "What is a hat-trick in cricket?": "Three Wickets",
    "First Cricket World Cup winner?": "West Indies",
    "Nickname of Sachin Ramesh Tendulkar?": "Master Blaster",
    "Trophy contested between England and Australia?": "The Ashes",
    "Cricket's highest governing body?": "International Cricket Council",
    "Who holds the record for most runs in ODI World Cups?": "Sachin Tendulkar",
    "Who was the first captain to win ICC ODI, T20 and Champions Trophy?": "Mahendra Singh Dhoni",
    "Who scored the fastest century in ODIs?": "AB de Villiers",
    "Which bowler took the first World Cup hat-trick?": "Chetan Sharma",
    "Who has the highest individual score in a World Cup match?": "Martin Guptill",
    "Who has the most wickets in World Cup history?": "Glenn McGrath",
    "Indian cricketer famous for helicopter shot?": "MS Dhoni",
    "Who is known as the Rawalpindi Express?": "Shoaib Akhtar",
    "Which country hosted the first ODI Cricket World Cup?": "England",
    "What is the maximum number of overs in an ODI?": "Fifty",
    "Who has the most Test wickets?": "Muttiah Muralitharan",
    "Who scored the first double century in ODI cricket?": "Sachin Tendulkar",
    "Who is known as The Wall in cricket?": "Rahul Dravid",
    "Who is the youngest cricketer to score a Test century?": "Mushtaq Mohammad",
    "Who was the highest wicket-taker in the 2019 Cricket World Cup?": "Mitchell Starc",
    "Who scored the most sixes in international cricket?": "Chris Gayle",
    "Who was the first cricketer to take 10 wickets in an innings?": "Jim Laker",
    "Who has the highest individual score in Test cricket?": "Brian Lara",
    "Which cricketer has the nickname 'Boom Boom'?": "Shahid Afridi",
    "Who captained India to its first Cricket World Cup win?": "Kapil Dev",
    # 20 Indian celebrities (full names)
    "Cricketer known as 'God of Cricket'?": "Sachin Ramesh Tendulkar",
    "Bollywood's King Khan?": "Shah Rukh Khan",
    "First Indian woman to win Miss World?": "Reita Faria",
    "Chairman and MD of Reliance Industries?": "Mukesh Ambani",
    "Indian singer who composed 'Jai Ho'?": "A.R. Rahman",
    "Youngest Indian Nobel laureate for education activism?": "Malala Yousafzai",
    "Famous Indian badminton player?": "Saina Nehwal",
    "Actor known as 'Megastar' in Telugu cinema?": "Chiranjeevi Konidela",
    "Indian female tennis player famous internationally?": "Sania Mirza",
    "Co-founder of Infosys?": "Narayana Murthy",
    "Indian Prime Minister in 2024?": "Narendra Modi",
    "Indian classical dancer known worldwide?": "Padma Subrahmanyam",
    "Critically acclaimed Bollywood actress?": "Deepika Padukone",
    "Indian boxing world champion?": "Mary Kom",
    "Indian film director of 'Lagaan'?": "Ashutosh Gowariker",
    "Head of Indian Space Research Organization (ISRO)?": "S. Somanath",
    "Indian origin CEO of Alphabet Inc.?": "Sundar Pichai",
    "Indian author of 'The White Tiger'?": "Aravind Adiga",
    "Indian footballer famous internationally?": "Sunil Chhetri",
    "Indian classical musician?": "Pandit Ravi Shankar",
    # 20 Random facts (with brief answers)
    "First human on the moon?": "Neil Armstrong",
    "Largest desert?": "Sahara",
    "Fastest land bird?": "Ostrich",
    "Deepest point on Earth?": "Challenger Deep",
    "Chemical symbol for water?": "H2O",
    "Tallest building (2025)?": "Burj Khalifa",
    "Fruit with most vitamin C?": "Guava",
    "Animal with trunk?": "Elephant",
    "Main gas in air?": "Nitrogen",
    "Largest bone in human body?": "Femur",
    "Planet shaped like a potato?": "Haumea",
    "Museum dedicated to failure?": "Museum of Failure",
    "Basketball court in Supreme Court?": "Highest court",
    "Office chair inventor?": "Charles Darwin",
    "Percentage of left-handed population?": "10 Percent",
    "Jeans tiny pocket purpose?": "Pocket watch",
    "Pope not allowed organ donor?": "True",
    "Only continent in four hemispheres?": "Africa",
    "Fastest growing plant?": "Bamboo",
    "Number of ridges on a US dime coin?": "118",
}
